2020-12-06 21:43:52,016 ERROR monkeybusiness.training.task.util.DataReader [main] ERROR
java.nio.file.NoSuchFileException: customers.txt
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:120) ~[?:?]
	at java.nio.channels.FileChannel.open(FileChannel.java:292) ~[?:?]
	at java.nio.channels.FileChannel.open(FileChannel.java:345) ~[?:?]
	at java.nio.file.Files.lines(Files.java:4037) ~[?:?]
	at java.nio.file.Files.lines(Files.java:4129) ~[?:?]
	at com.monkeybusiness.training.task.util.DataReader.readCustomerFromFile(DataReader.java:34) [classes/:?]
	at com.monkeybusiness.training.task.main.Main.main(Main.java:18) [classes/:?]
2020-12-06 21:46:49,747 ERROR monkeybusiness.training.task.util.DataReader [main] ERROR
java.nio.file.NoSuchFileException: customers.txt
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:120) ~[?:?]
	at java.nio.channels.FileChannel.open(FileChannel.java:292) ~[?:?]
	at java.nio.channels.FileChannel.open(FileChannel.java:345) ~[?:?]
	at java.nio.file.Files.lines(Files.java:4037) ~[?:?]
	at java.nio.file.Files.lines(Files.java:4129) ~[?:?]
	at com.monkeybusiness.training.task.util.DataReader.readCustomerFromFile(DataReader.java:34) [classes/:?]
	at com.monkeybusiness.training.task.main.Main.main(Main.java:18) [classes/:?]
2020-12-06 21:47:29,317 ERROR monkeybusiness.training.task.util.DataReader [main] ERROR
java.nio.file.NoSuchFileException: customers.txt
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:120) ~[?:?]
	at java.nio.channels.FileChannel.open(FileChannel.java:292) ~[?:?]
	at java.nio.channels.FileChannel.open(FileChannel.java:345) ~[?:?]
	at java.nio.file.Files.lines(Files.java:4037) ~[?:?]
	at java.nio.file.Files.lines(Files.java:4129) ~[?:?]
	at com.monkeybusiness.training.task.util.DataReader.readCustomerFromFile(DataReader.java:34) [classes/:?]
	at com.monkeybusiness.training.task.main.Main.main(Main.java:19) [classes/:?]
2020-12-06 22:09:06,392 ERROR monkeybusiness.training.task.util.DataReader [main] ERROR
java.nio.file.NoSuchFileException: res\customers.txt
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:120) ~[?:?]
	at java.nio.channels.FileChannel.open(FileChannel.java:292) ~[?:?]
	at java.nio.channels.FileChannel.open(FileChannel.java:345) ~[?:?]
	at java.nio.file.Files.lines(Files.java:4037) ~[?:?]
	at java.nio.file.Files.lines(Files.java:4129) ~[?:?]
	at com.monkeybusiness.training.task.util.DataReader.readCustomerFromFile(DataReader.java:35) [classes/:?]
	at com.monkeybusiness.training.task.util.DataReader.readCustomerFromFile(DataReader.java:50) [classes/:?]
	at com.monkeybusiness.training.task.main.Main.main(Main.java:19) [classes/:?]
2020-12-06 22:09:23,105 ERROR monkeybusiness.training.task.util.DataReader [main] ERROR
java.nio.file.NoSuchFileException: res\customers.txt
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:120) ~[?:?]
	at java.nio.channels.FileChannel.open(FileChannel.java:292) ~[?:?]
	at java.nio.channels.FileChannel.open(FileChannel.java:345) ~[?:?]
	at java.nio.file.Files.lines(Files.java:4037) ~[?:?]
	at java.nio.file.Files.lines(Files.java:4129) ~[?:?]
	at com.monkeybusiness.training.task.util.DataReader.readCustomerFromFile(DataReader.java:35) [classes/:?]
	at com.monkeybusiness.training.task.util.DataReader.readCustomerFromFile(DataReader.java:50) [classes/:?]
	at com.monkeybusiness.training.task.main.Main.main(Main.java:19) [classes/:?]
2020-12-06 22:09:34,591 ERROR monkeybusiness.training.task.util.DataReader [main] ERROR
java.nio.file.NoSuchFileException: res\customers.txt
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:120) ~[?:?]
	at java.nio.channels.FileChannel.open(FileChannel.java:292) ~[?:?]
	at java.nio.channels.FileChannel.open(FileChannel.java:345) ~[?:?]
	at java.nio.file.Files.lines(Files.java:4037) ~[?:?]
	at java.nio.file.Files.lines(Files.java:4129) ~[?:?]
	at com.monkeybusiness.training.task.util.DataReader.readCustomerFromFile(DataReader.java:35) [classes/:?]
	at com.monkeybusiness.training.task.util.DataReader.readCustomerFromFile(DataReader.java:50) [classes/:?]
	at com.monkeybusiness.training.task.main.Main.main(Main.java:19) [classes/:?]
2020-12-06 22:17:08,160 ERROR monkeybusiness.training.task.util.DataReader [main] ERROR
java.nio.file.NoSuchFileException: data\res\customers.txt
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:120) ~[?:?]
	at java.nio.channels.FileChannel.open(FileChannel.java:292) ~[?:?]
	at java.nio.channels.FileChannel.open(FileChannel.java:345) ~[?:?]
	at java.nio.file.Files.lines(Files.java:4037) ~[?:?]
	at java.nio.file.Files.lines(Files.java:4129) ~[?:?]
	at com.monkeybusiness.training.task.util.DataReader.readCustomerFromFile(DataReader.java:35) [classes/:?]
	at com.monkeybusiness.training.task.util.DataReader.readCustomerFromFile(DataReader.java:50) [classes/:?]
	at com.monkeybusiness.training.task.main.Main.main(Main.java:19) [classes/:?]
2020-12-06 22:17:40,618 ERROR monkeybusiness.training.task.util.DataReader [main] ERROR
java.nio.file.NoSuchFileException: data\res\customers.txt
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:120) ~[?:?]
	at java.nio.channels.FileChannel.open(FileChannel.java:292) ~[?:?]
	at java.nio.channels.FileChannel.open(FileChannel.java:345) ~[?:?]
	at java.nio.file.Files.lines(Files.java:4037) ~[?:?]
	at java.nio.file.Files.lines(Files.java:4129) ~[?:?]
	at com.monkeybusiness.training.task.util.DataReader.readCustomerFromFile(DataReader.java:35) [classes/:?]
	at com.monkeybusiness.training.task.util.DataReader.readCustomerFromFile(DataReader.java:50) [classes/:?]
	at com.monkeybusiness.training.task.main.Main.main(Main.java:19) [classes/:?]
2020-12-06 23:16:44,025 ERROR task.model.service.impl.CustomerServiceImpl [main] ERROR
com.monkeybusiness.training.task.exception.DaoException: Customer already exists...
	at com.monkeybusiness.training.task.model.dao.impl.CustomerDaoImpl.add(CustomerDaoImpl.java:26) ~[classes/:?]
	at com.monkeybusiness.training.task.model.dao.impl.CustomerDaoImpl.addAll(CustomerDaoImpl.java:35) ~[classes/:?]
	at com.monkeybusiness.training.task.model.dao.impl.CustomerDaoImpl.updateAll(CustomerDaoImpl.java:69) ~[classes/:?]
	at com.monkeybusiness.training.task.model.service.impl.CustomerServiceImpl.sort(CustomerServiceImpl.java:153) [classes/:?]
	at com.monkeybusiness.training.task.model.service.impl.CustomerServiceImpl.sortById(CustomerServiceImpl.java:165) [classes/:?]
	at com.monkeybusiness.training.task.model.service.impl.CustomerServiceImplTest.testSortById(CustomerServiceImplTest.java:40) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80) [testng-6.8.jar:?]
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714) [testng-6.8.jar:?]
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901) [testng-6.8.jar:?]
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231) [testng-6.8.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127) [testng-6.8.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111) [testng-6.8.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:767) [testng-6.8.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:617) [testng-6.8.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334) [testng-6.8.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329) [testng-6.8.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291) [testng-6.8.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:240) [testng-6.8.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-6.8.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86) [testng-6.8.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198) [testng-6.8.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123) [testng-6.8.jar:?]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-6.8.jar:?]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
2020-12-06 23:17:59,015 ERROR task.model.service.impl.CustomerServiceImpl [main] ERROR
com.monkeybusiness.training.task.exception.DaoException: Customer already exists...
	at com.monkeybusiness.training.task.model.dao.impl.CustomerDaoImpl.add(CustomerDaoImpl.java:26) ~[classes/:?]
	at com.monkeybusiness.training.task.model.dao.impl.CustomerDaoImpl.addAll(CustomerDaoImpl.java:35) ~[classes/:?]
	at com.monkeybusiness.training.task.model.dao.impl.CustomerDaoImpl.updateAll(CustomerDaoImpl.java:69) ~[classes/:?]
	at com.monkeybusiness.training.task.model.service.impl.CustomerServiceImpl.sort(CustomerServiceImpl.java:153) [classes/:?]
	at com.monkeybusiness.training.task.model.service.impl.CustomerServiceImpl.sortById(CustomerServiceImpl.java:165) [classes/:?]
	at com.monkeybusiness.training.task.model.service.impl.CustomerServiceImplTest.testSortById(CustomerServiceImplTest.java:40) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80) [testng-6.8.jar:?]
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714) [testng-6.8.jar:?]
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901) [testng-6.8.jar:?]
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231) [testng-6.8.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127) [testng-6.8.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111) [testng-6.8.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:767) [testng-6.8.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:617) [testng-6.8.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334) [testng-6.8.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329) [testng-6.8.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291) [testng-6.8.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:240) [testng-6.8.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-6.8.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86) [testng-6.8.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198) [testng-6.8.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123) [testng-6.8.jar:?]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-6.8.jar:?]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
2020-12-06 23:23:34,297 ERROR task.model.service.impl.CustomerServiceImpl [main] ERROR
com.monkeybusiness.training.task.exception.DaoException: Customer already exists...
	at com.monkeybusiness.training.task.model.dao.impl.CustomerDaoImpl.add(CustomerDaoImpl.java:26) ~[classes/:?]
	at com.monkeybusiness.training.task.model.dao.impl.CustomerDaoImpl.addAll(CustomerDaoImpl.java:35) ~[classes/:?]
	at com.monkeybusiness.training.task.model.dao.impl.CustomerDaoImpl.updateAll(CustomerDaoImpl.java:69) ~[classes/:?]
	at com.monkeybusiness.training.task.model.service.impl.CustomerServiceImpl.sort(CustomerServiceImpl.java:153) [classes/:?]
	at com.monkeybusiness.training.task.model.service.impl.CustomerServiceImpl.sortById(CustomerServiceImpl.java:165) [classes/:?]
	at com.monkeybusiness.training.task.model.service.impl.CustomerServiceImplTest.testSortById(CustomerServiceImplTest.java:40) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80) [testng-6.8.jar:?]
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714) [testng-6.8.jar:?]
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901) [testng-6.8.jar:?]
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231) [testng-6.8.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127) [testng-6.8.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111) [testng-6.8.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:767) [testng-6.8.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:617) [testng-6.8.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334) [testng-6.8.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329) [testng-6.8.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291) [testng-6.8.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:240) [testng-6.8.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-6.8.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86) [testng-6.8.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198) [testng-6.8.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123) [testng-6.8.jar:?]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-6.8.jar:?]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
2020-12-06 23:25:26,020 ERROR task.model.service.impl.CustomerServiceImpl [main] ERROR
com.monkeybusiness.training.task.exception.DaoException: Customer already exists...
	at com.monkeybusiness.training.task.model.dao.impl.CustomerDaoImpl.add(CustomerDaoImpl.java:26) ~[classes/:?]
	at com.monkeybusiness.training.task.model.dao.impl.CustomerDaoImpl.addAll(CustomerDaoImpl.java:35) ~[classes/:?]
	at com.monkeybusiness.training.task.model.dao.impl.CustomerDaoImpl.updateAll(CustomerDaoImpl.java:69) ~[classes/:?]
	at com.monkeybusiness.training.task.model.service.impl.CustomerServiceImpl.sort(CustomerServiceImpl.java:153) [classes/:?]
	at com.monkeybusiness.training.task.model.service.impl.CustomerServiceImpl.sortById(CustomerServiceImpl.java:165) [classes/:?]
	at com.monkeybusiness.training.task.model.service.impl.CustomerServiceImplTest.testSortById(CustomerServiceImplTest.java:42) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80) [testng-6.8.jar:?]
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714) [testng-6.8.jar:?]
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901) [testng-6.8.jar:?]
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231) [testng-6.8.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127) [testng-6.8.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111) [testng-6.8.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:767) [testng-6.8.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:617) [testng-6.8.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334) [testng-6.8.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329) [testng-6.8.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291) [testng-6.8.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:240) [testng-6.8.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-6.8.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86) [testng-6.8.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198) [testng-6.8.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123) [testng-6.8.jar:?]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-6.8.jar:?]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
2020-12-06 23:26:20,737 ERROR task.model.service.impl.CustomerServiceImpl [main] ERROR
com.monkeybusiness.training.task.exception.DaoException: Customer already exists...
	at com.monkeybusiness.training.task.model.dao.impl.CustomerDaoImpl.add(CustomerDaoImpl.java:26) ~[classes/:?]
	at com.monkeybusiness.training.task.model.dao.impl.CustomerDaoImpl.addAll(CustomerDaoImpl.java:35) ~[classes/:?]
	at com.monkeybusiness.training.task.model.dao.impl.CustomerDaoImpl.updateAll(CustomerDaoImpl.java:69) ~[classes/:?]
	at com.monkeybusiness.training.task.model.service.impl.CustomerServiceImpl.sort(CustomerServiceImpl.java:153) [classes/:?]
	at com.monkeybusiness.training.task.model.service.impl.CustomerServiceImpl.sortById(CustomerServiceImpl.java:165) [classes/:?]
	at com.monkeybusiness.training.task.model.service.impl.CustomerServiceImplTest.testSortById(CustomerServiceImplTest.java:42) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80) [testng-6.8.jar:?]
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714) [testng-6.8.jar:?]
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901) [testng-6.8.jar:?]
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231) [testng-6.8.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127) [testng-6.8.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111) [testng-6.8.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:767) [testng-6.8.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:617) [testng-6.8.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334) [testng-6.8.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329) [testng-6.8.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291) [testng-6.8.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:240) [testng-6.8.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-6.8.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86) [testng-6.8.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198) [testng-6.8.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123) [testng-6.8.jar:?]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-6.8.jar:?]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
